name: Jest Test

on:
  pull_request:

jobs:
  jest-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node: [16.x, 17.x, 18.x, 19.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      run: npm test
